### ISSUE TITLE
Pyxll: How to call dataframe in excel

### ISSUE THREAD

**Issue by joginderrohilla** [pyxll/pyxll-examples#7]
My code:
@xl_func()
def GetpdfData():
    tables = camelot.read_pdf('E:\Idoc\pyxll\Test\pdftable2.pdf',flavor='lattice', pages='1-2')
    return tables[1].df

its working on python environment and print table. When I call it from excel using Pyxll, it retruns below:
![image](https://user-images.githubusercontent.com/60636357/81191048-2ed97d00-8fd6-11ea-9fda-db81155070f6.png)

please help, urgent requirment.

**Comment by tonyroberts** [comment]
Hi,

if you need to return the dataframe as a range in Excel you need to use the "dataframe" return type. For example, change your function to:

```python
@xl_func(": dataframe", auto_resize=True)
def GetpdfData():
    tables = camelot.read_pdf('E:\Idoc\pyxll\Test\pdftable2.pdf',flavor='lattice', pages='1-2')
    return tables[1].df
```

Above I have added the function signature to @xl_func to specify the return type to apply the right converter to convert it to an array before returning to Excel. I have also added "auto_resize=True" so that the array function will resize automatically.

You can find more information about his in the docs here: https://www.pyxll.com/docs/userguide/pandas.html

For support please contact us via the website https://www.pyxll.com/support.html or email us rather than create an issue here.

Best regards,
Tony
